name: ditonton
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  about:
    path: about
  animate_do: ^2.1.0
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  core:
    path: core
  cupertino_icons: ^1.0.4
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.6
  flutter_rating_bar: ^4.0.0
  get_it: ^7.2.0
  google_fonts: ^2.2.0
  http: ^0.13.4
  intl: ^0.17.0
  introduction_screen: ^3.0.2
  movie:
    path: movie
  path_provider: ^2.0.8
  provider: ^6.0.2
  search:
    path: search
  shared_preferences: ^2.0.13
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  sqflite: ^2.0.1
  tv:
    path: tv
  youtube_player_flutter: ^8.0.0

dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.0.17

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  image: assets/splash.png
  color: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/
